<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Media;
use App\Models\Place;
use App\Models\Source;
use App\Models\TimelineEvent;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $sources = [
            ['title' => 'Tulipa greigii Regel', 'author' => 'Royal Botanic Gardens, Kew — Plants of the World Online', 'year' => '2026', 'kind' => 'Ғылыми таксономиялық дерек', 'url' => 'https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:542931-1/general-information', 'note' => ['kz' => 'Қабылданған атауы мен ғылыми жарияланым дерегі.', 'ru' => 'Принятое название и данные научной публикации.', 'en' => 'Accepted name and publication record.']],
            ['title' => 'Tulipa greigi Regel', 'author' => 'International Plant Names Index', 'year' => '1873', 'kind' => 'Бастапқы библиографиялық жазба', 'url' => 'https://www.ipni.org/n/542931-1', 'note' => ['kz' => 'Gartenflora 22: 290 (1873) жазбасын көрсетеді.', 'ru' => 'Запись указывает Gartenflora 22: 290 (1873).', 'en' => 'The record cites Gartenflora 22: 290 (1873).']],
            ['title' => 'Revisiting the genus Tulipa in Kazakhstan', 'author' => 'Turczaninowia / PubMed Central', 'year' => '2024', 'kind' => 'Рецензияланған ғылыми мақала', 'url' => 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11686166/', 'note' => ['kz' => 'Қазақстан қызғалдақтарының таксономиясы мен таралуын қайта қарау.', 'ru' => 'Таксономический обзор и распространение тюльпанов Казахстана.', 'en' => 'A taxonomic review of Kazakhstan tulips and their distribution.']],
            ['title' => 'Қазығұртта Грейг қызғалдағы гүлдеді', 'author' => 'Түркістан облысы әкімдігінің ресми сайты', 'year' => '2026', 'kind' => 'Ресми хабарлама', 'url' => 'https://www.gov.kz/memleket/entities/ontustik/press/news/details/1192637', 'note' => ['kz' => 'Қазығұрт ауданындағы өсімдіктің гүлдеуін хабарлайды.', 'ru' => 'Сообщение о цветении вида в Казыгуртском районе.', 'en' => 'Reports flowering in the Kazygurt district.']],
            ['title' => 'Tulipa greigii Gartenflora 22, plate 773', 'author' => 'Biodiversity Heritage Library', 'year' => '1873', 'kind' => 'Тарихи ботаникалық иллюстрация', 'url' => 'https://www.biodiversitylibrary.org/page/47574892', 'note' => ['kz' => '1873 жылғы түпнұсқа басылым беті.', 'ru' => 'Страница оригинального издания 1873 года.', 'en' => 'Digitized page from the original 1873 publication.']],
            ['title' => 'The Silk Roads: Routes Network of Chang’an–Tianshan Corridor', 'author' => 'UNESCO World Heritage Centre', 'year' => '2014', 'kind' => 'Дүниежүзілік мұра дерегі', 'url' => 'https://whc.unesco.org/en/list/1442/', 'note' => ['kz' => 'Жібек жолы мәдени дәлізінің тарихи контексті; қызғалдақ тасымалын дәлелдемейді.', 'ru' => 'Исторический контекст коридора; не доказывает перевозку тюльпана.', 'en' => 'Historical corridor context; does not document tulip transport.']],
            ['title' => 'Silk Roads: Fergana-Syrdarya Corridor', 'author' => 'UNESCO World Heritage Centre — Tentative List', 'year' => '2021', 'kind' => 'ЮНЕСКО алдын ала тізімі', 'url' => 'https://whc.unesco.org/en/tentativelists/6568/', 'note' => ['kz' => 'Қазақстан ұсынған алдын ала тізімдегі дәліз; Отырар мен Ясы-Түркістанды қамтиды.', 'ru' => 'Предложенный Казахстаном коридор из Предварительного списка; включает Отрар и Яссы-Туркестан.', 'en' => 'A Kazakhstan-submitted corridor on the Tentative List; includes Otrar and Yassy-Turkistan.']],
            ['title' => 'Сайрам (Испиджаб)', 'author' => 'Қазақстанның киелі жерлерінің географиясы — oq.gov.kz', 'year' => '2026', 'kind' => 'Ресми тарихи дерек', 'url' => 'https://oq.gov.kz/ru/abai/sayram-ispiddgab', 'note' => ['kz' => 'Сайрамның ортағасырлық сауда және мәдени орталық ретіндегі тарихы.', 'ru' => 'История Сайрама как средневекового торгового и культурного центра.', 'en' => 'Sayram as a medieval trade and cultural centre.']],
            ['title' => 'Aksu-Zhabagly Biosphere Reserve', 'author' => 'UNESCO — Man and the Biosphere Programme', 'year' => '2026', 'kind' => 'Табиғи мұра дерегі', 'url' => 'https://www.unesco.org/en/mab/aksu-zhabagly', 'note' => ['kz' => 'Ақсу-Жабағылы биосфералық резерватының Батыс Тянь-Шаньдағы орны.', 'ru' => 'Аксу-Жабаглы в Западном Тянь-Шане.', 'en' => 'Aksu-Zhabagly in the Western Tien-Shan.']],
            ['title' => 'Where and when to enjoy tulip blossom in Kazakhstan', 'author' => 'Kazakhstan.travel — national tourism portal', 'year' => null, 'kind' => 'Табиғи мұра дерегі', 'url' => 'https://www.kazakhstan.travel/ru/publications/when-and-where-to-enjoy-the-blossoming-of-tulips-in-kazakhstan', 'note' => ['kz' => 'Грейг қызғалдағы кездесетін қорғалатын аумақтар қатарында Жамбыл облысындағы Берқара қорықшасы көрсетілген.', 'ru' => 'Среди охраняемых территорий с тюльпаном Грейга указано урочище Беркара в Жамбылской области.', 'en' => 'Lists the Berkara Sanctuary in Zhambyl Region among protected areas with Greig’s tulip populations.']],
            ['title' => 'Шұбайқызыл алауы-2026 festival in Tulkibas', 'author' => 'Turkistan Region akimat — gov.kz', 'year' => '2026', 'kind' => 'Ресми ақпарат', 'url' => 'https://beta.egov.kz/memleket/entities/ontustik/press/news/details/1204055', 'note' => ['kz' => 'Түлкібастағы Шұбайқызыл қызғалдағы фестивалі туралы ресми хабарлама; түрді Tulipa greigii деп анықтамайды.', 'ru' => 'Официальное сообщение о фестивале тюльпана Шубайкызыл в Тюлькубасе; вид не указан как Tulipa greigii.', 'en' => 'Official report on the Shubaykyzyl tulip festival in Tulkibas; it does not identify the flower as Tulipa greigii.']],
            ['title' => 'Kazakhstan tulips: comparative analysis of chloroplast genomes', 'author' => 'Frontiers in Plant Science — peer-reviewed research', 'year' => '2024', 'kind' => 'Рецензияланған ғылыми мақала', 'url' => 'https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2024.1433253/full', 'note' => ['kz' => 'Түр морфологиясы, таралуы және IUCN бағасы туралы ашық зерттеу.', 'ru' => 'Открытое исследование морфологии, распространения и оценки IUCN.', 'en' => 'Open study on morphology, distribution and the IUCN assessment.']],
            ['title' => 'Tulipa greigii — plant record', 'author' => 'University of Cambridge Botanic Garden', 'year' => null, 'kind' => 'Ботаникалық бақ дерегі', 'url' => 'https://www.botanic.cam.ac.uk/the-garden/plant-list/tulipa-greigii/', 'note' => ['kz' => 'Гүлдің сыртқы белгілері мен бақ мәдениетін сипаттайтын карточка.', 'ru' => 'Карточка с признаками цветка и сведениями о садовой культуре.', 'en' => 'A plant record describing flower characters and horticultural context.']],
            ['title' => 'Tulipa greigii Regel — specimen P00730913', 'author' => 'Muséum national d’Histoire naturelle, Paris', 'year' => '1872', 'kind' => 'Музей гербарийі', 'url' => 'https://science.mnhn.fr/institution/mnhn/collection/p/item/p00730913', 'note' => ['kz' => 'Жинау күні мен жергіліктігі көрсетілген гербарий карточкасы; тип мәртебесі белгісіз.', 'ru' => 'Гербарная запись с датой сбора и местом; статус типа не определён.', 'en' => 'Herbarium record with collection date and locality; type status is uncertain.']],
            ['title' => 'Tulipa greigii Gartenflora 22, plate 773 (1873)', 'author' => 'Eduard August von Regel — BHL / Wikimedia Commons', 'year' => '1873', 'kind' => 'Ашық архивтік иллюстрация', 'url' => 'https://commons.wikimedia.org/wiki/File:Tulipa_greigii_Gartenflora_22_t_773_(1873).jpg', 'note' => ['kz' => 'Public Domain Mark 1.0 белгісі бар түпнұсқа ботаникалық сурет.', 'ru' => 'Оригинальная ботаническая иллюстрация с отметкой Public Domain Mark 1.0.', 'en' => 'Original botanical illustration marked Public Domain Mark 1.0.']],
            ['title' => 'Seven reasons to visit Shymkent — tulip in city identity', 'author' => 'Shymkent Tourism — official city tourism portal', 'year' => null, 'kind' => 'Қалалық мұра', 'url' => 'https://www.gov.kz/memleket/entities/shymkent-turizm/press/news/details/72607?lang=en', 'note' => ['kz' => 'Туристік органның қалалық символика мен көктемгі гүл отырғызу туралы сипаттамасы.', 'ru' => 'Описание городской символики и весенних посадок тюльпанов от туристического ведомства.', 'en' => 'Tourism office record of civic tulip symbolism and spring planting.']],
        ];
        foreach ($sources as $i => $data) Source::updateOrCreate(['title' => $data['title']], $data + ['sort_order' => $i]);

        $places = [
            ['slug' => 'aqsu-zhabagly', 'name' => ['kz'=>'Ақсу-Жабағылы','ru'=>'Аксу-Жабаглы','en'=>'Aksu-Zhabagly'], 'region' => 'Батыс Тянь-Шань', 'coordinates' => ['lat'=>42.35,'lng'=>70.55], 'summary' => ['kz'=>'Батыс Тянь-Шаньның биік таулы табиғатымен таныстыратын қорғалатын аумақ.','ru'=>'Охраняемая территория с высокогорными ландшафтами Западного Тянь-Шаня.','en'=>'A protected area known for the high mountain landscapes of the Western Tien-Shan.'], 'history' => ['kz'=>'Аймақтың табиғи тарихы қорғалатын аумақтар мен ғылыми зерттеулер арқылы танылады.','ru'=>'Природная история региона раскрывается через охраняемые территории и научные исследования.','en'=>'The region’s natural history is interpreted through protected landscapes and research.'], 'nature' => ['kz'=>'Жергілікті флораны қорғау мен бақылауға арналған маңызды табиғи орта.','ru'=>'Важная природная среда для охраны и наблюдения за местной флорой.','en'=>'An important setting for the conservation and study of local flora.'], 'sort_order'=>0],
            ['slug' => 'kazygurt', 'name' => ['kz'=>'Қазығұрт','ru'=>'Казыгурт','en'=>'Kazygurt'], 'region' => 'Түркістан облысы', 'coordinates' => ['lat'=>41.77,'lng'=>69.92], 'summary' => ['kz'=>'Түркістан облысындағы тау бөктері мен көктемгі дала көріністері түйісетін өлке.','ru'=>'Предгорный ландшафт Туркестанской области с весенними степными видами.','en'=>'A foothill landscape in Turkistan Region, known for its spring steppe scenery.'], 'history' => ['kz'=>'Қазығұрт — Оңтүстік Қазақстанның мәдени географиясындағы танымал атаулардың бірі.','ru'=>'Казыгурт — одно из известных названий культурной географии Южного Казахстана.','en'=>'Kazygurt is one of the familiar place names in Southern Kazakhstan’s cultural geography.'], 'nature' => ['kz'=>'Ресми өңірлік хабарлама Қазығұрт ауданында Грейг қызғалдағының гүлдегенін тіркеген.','ru'=>'Официальное сообщение региона отмечает цветение тюльпана Грейга в Казыгуртском районе.','en'=>'An official regional notice records Greig’s tulip flowering in Kazygurt district.'], 'sort_order'=>1],
            ['slug' => 'shymkent', 'name' => ['kz'=>'Шымкент','ru'=>'Шымкент','en'=>'Shymkent'], 'region' => 'Қазақстан', 'coordinates' => ['lat'=>42.34,'lng'=>69.59], 'summary' => ['kz'=>'Оңтүстіктің ірі қаласы — табиғи мұра туралы әңгіменің бүгінгі қалалық тарауы.','ru'=>'Крупный южный город — современная городская глава истории природного наследия.','en'=>'A major southern city and the contemporary urban chapter of this natural heritage story.'], 'history' => ['kz'=>'Қала мен өңір тарихын бір-бірінен бөлек емес, ортақ мәдени ландшафт ретінде қарастырамыз.','ru'=>'Рассматриваем город и регион как общий культурный ландшафт.','en'=>'The city and region are presented as parts of one cultural landscape.'], 'nature' => ['kz'=>'Қалалық кеңістікте табиғат туралы білімді жеткізу мен қорғауды насихаттау маңызды.','ru'=>'Городское пространство помогает рассказывать о природе и бережном отношении к ней.','en'=>'Urban spaces can make nature knowledge and conservation visible.'], 'sort_order'=>2],
            ['slug' => 'turkistan', 'name' => ['kz'=>'Түркістан','ru'=>'Туркестан','en'=>'Turkistan'], 'region' => 'Түркістан облысы', 'coordinates' => ['lat'=>43.30,'lng'=>68.25], 'summary' => ['kz'=>'Тарихи қалалық мұрасы бар өңір орталығы.','ru'=>'Региональный центр с богатым историческим городским наследием.','en'=>'A regional centre with a rich historic urban heritage.'], 'history' => ['kz'=>'Түркістан Жібек жолы дәліздерінің кең тарихи-мәдени контекстіне кіреді.','ru'=>'Туркестан связан с широким историко-культурным контекстом шелковых коридоров.','en'=>'Turkistan belongs to the wider historical and cultural context of Silk Roads corridors.'], 'nature' => ['kz'=>'Бұл жобада табиғи мұра қаланың тарихи баянымен қатар көрсетіледі.','ru'=>'В проекте природное наследие показано рядом с историей города.','en'=>'This project presents natural heritage alongside the city’s history.'], 'sort_order'=>3],
            ['slug' => 'otrar', 'name' => ['kz'=>'Отырар','ru'=>'Отрар','en'=>'Otrar'], 'region' => 'Түркістан облысы', 'coordinates' => ['lat'=>42.85,'lng'=>68.30], 'summary' => ['kz'=>'Оңтүстік өңірдің тарихи қалалық ландшафтын зерттейтін орын.','ru'=>'Место для изучения исторического городского ландшафта южного региона.','en'=>'A place for exploring the southern region’s historic urban landscape.'], 'history' => ['kz'=>'Қазақстан ұсынған алдын ала тізімдегі Ферғана–Сырдария дәлізінің бөлігі.','ru'=>'Часть предложенного Казахстаном коридора Фергана–Сырдарья из Предварительного списка.','en'=>'Part of Kazakhstan’s proposed Fergana-Syrdarya Corridor on the Tentative List.'], 'nature' => ['kz'=>'Бұл картадағы нүкте — тарихи бағдар; қызғалдақтың сауда жолымен өткеніне дәлел емес.','ru'=>'Метка на карте — исторический ориентир, а не доказательство перевозки тюльпана.','en'=>'The map marker is a historical orientation point, not evidence of tulip transport.'], 'sort_order'=>4],
            ['slug' => 'sayram', 'name' => ['kz'=>'Сайрам','ru'=>'Сайрам','en'=>'Sayram'], 'region' => 'Түркістан облысы', 'coordinates' => ['lat'=>42.31,'lng'=>69.76], 'summary' => ['kz'=>'Шымкент маңындағы тарихи қалалық мекен.','ru'=>'Историческое городское место рядом с Шымкентом.','en'=>'Historic urban site near Shymkent.'], 'history' => ['kz'=>'Ресми материалдарда Сайрам (Испиджаб) ортағасырлық сауда және мәдени орталық ретінде сипатталады.','ru'=>'Официальные материалы описывают Сайрам (Испиджаб) как средневековый торговый и культурный центр.','en'=>'Official background describes Sayram (Isfijab) as a medieval trade and cultural centre.'], 'nature' => ['kz'=>'Өңірдің қалалық тарихы өсімдіктің ғылыми тарихынан бөлек көрсетіледі.','ru'=>'История города отделена от научной истории растения.','en'=>'The city’s history is kept distinct from the plant’s scientific record.'], 'sort_order'=>5],
            ['slug' => 'tulkibas', 'name' => ['kz'=>'Түлкібас','ru'=>'Тюлькубас','en'=>'Tulkibas'], 'region' => 'Түркістан облысы', 'coordinates' => ['lat'=>42.49,'lng'=>70.29], 'summary' => ['kz'=>'Шұбайқызыл қызғалдағы фестивалі туралы 2026 жылғы ресми хабарлама жарияланған аудан орталығы.','ru'=>'Районный центр, о фестивале тюльпана Шубайкызыл в котором опубликовано официальное сообщение за 2026 год.','en'=>'District centre featured in an official 2026 report about the Shubaykyzyl tulip festival.'], 'history' => ['kz'=>'Нүкте аудан орталығын белгілейді; хабарлама Грейг қызғалдағының дәл осы жерде өсетінін растамайды.','ru'=>'Метка обозначает центр района; источник не подтверждает, что именно здесь растёт тюльпан Грейга.','en'=>'The marker identifies the district centre; the source does not establish a local population of Greig’s tulip.'], 'nature' => ['kz'=>'Шұбайқызыл туралы фестиваль дерегі Грейг қызғалдағына қатысты дерек ретінде қолданылмайды.','ru'=>'Сообщение о фестивале Шубайкызыл не используется как источник о тюльпане Грейга.','en'=>'The Shubaykyzyl festival report is not treated as evidence about Greig’s tulip.'], 'sort_order'=>6],
            ['slug' => 'berkara', 'name' => ['kz'=>'Берікқара','ru'=>'Беркара','en'=>'Berkara Tract'], 'region' => 'Жамбыл облысы · Қаратау', 'coordinates' => ['lat'=>42.903,'lng'=>70.616], 'summary' => ['kz'=>'Туризм порталы Грейг қызғалдағы кездесетін Жамбыл облысының қорғалатын аумақтарының бірі ретінде атайды.','ru'=>'Туристический портал указывает его среди охраняемых территорий Жамбылской области с тюльпаном Грейга.','en'=>'A tourism portal lists it among protected areas in Zhambyl Region with Greig’s tulip populations.'], 'history' => ['kz'=>'Картадағы координата — Берқара шатқалының шамамен алынған орны, нақты өсімдік популяциясының нүктесі емес.','ru'=>'Координаты показывают примерное положение ущелья Беркара, а не точку популяции растения.','en'=>'The coordinate is an approximate gorge location, not a plant population point.'], 'nature' => ['kz'=>'Сирек өсімдіктердің дәл мекенін жарияламаңыз.','ru'=>'Точные места редких растений публиковать не следует.','en'=>'Precise sites of rare plants should not be published.'], 'sort_order'=>7],
        ];
        foreach ($places as $place) Place::updateOrCreate(['slug' => $place['slug']], $place);

        $source = Source::first();
        $events = [
            ['date_label'=>'Өлке тарихы','title'=>['kz'=>'Ежелгі Оңтүстік Қазақстан','ru'=>'Древний Южный Казахстан','en'=>'Ancient Southern Kazakhstan'],'description'=>['kz'=>'Археология, қалалар мен ландшафттар аймақтың ұзақ тарихын танытады. Бұл тарау Грейг қызғалдағы туралы деректермен шатастырылмайды.','ru'=>'Археология, города и ландшафты рассказывают о долгой истории региона. Этот контекст не следует смешивать с фактами о тюльпане Грейга.','en'=>'Archaeology, cities and landscapes tell a long regional story. This context is kept distinct from evidence about Greig’s tulip.']],
            ['date_label'=>'Жібек жолы дәуірі','title'=>['kz'=>'Мәдени байланыстар дәлізі','ru'=>'Коридор культурных связей','en'=>'A corridor of cultural exchange'],'description'=>['kz'=>'Сайрам, Отырар және Түркістан өңірі Еуразияның тарихи байланыстары туралы кең әңгімеге жол ашады. Өсімдіктің Еуропаға дәл осы жолмен жеткізілгені дәлелденбеген.','ru'=>'Сайрам, Отрар и Туркестан включают регион в широкий рассказ о связях Евразии. Перемещение растения в Европу именно этим путём документально не установлено.','en'=>'Sayram, Otrar and Turkistan connect the region to a wider Eurasian history. A specific route carrying this tulip to Europe is not documented here.']],
            ['date_label'=>'1873','title'=>['kz'=>'Ғылыми сипаттамасы жарияланды','ru'=>'Опубликовано научное описание','en'=>'Scientific description published'],'description'=>['kz'=>'Kew мен IPNI деректері Tulipa greigii атауының 1873 жылы Gartenflora 22:290 бетінде алғаш жарияланғанын көрсетеді.','ru'=>'По данным Kew и IPNI, название Tulipa greigii впервые опубликовано в 1873 году: Gartenflora 22:290.','en'=>'Kew and IPNI record the first publication of the name Tulipa greigii in 1873: Gartenflora 22:290.']],
            ['date_label'=>'Бүгін','title'=>['kz'=>'Зерттеу және сақтау','ru'=>'Изучение и сохранение','en'=>'Study and conservation'],'description'=>['kz'=>'Қазақстандағы қызғалдақтардың қазіргі ғылыми таксономиясы қайта қаралып келеді; түрлерді тану мен тіршілік ортасын сақтау бірге жүреді.','ru'=>'Современная систематика тюльпанов Казахстана уточняется; изучение видов связано с сохранением местообитаний.','en'=>'Taxonomy of Kazakhstan’s tulips continues to be reviewed; species study goes together with habitat conservation.']],
            ['date_label'=>'Ертең','title'=>['kz'=>'Болашаққа аманат','ru'=>'Наследие для будущего','en'=>'A legacy for the future'],'description'=>['kz'=>'Цифрлық мұрағат жергілікті білімді, дереккөздерді және табиғатқа жауапкершілікті келесі ұрпаққа жеткізудің бір жолы.','ru'=>'Цифровой архив помогает передавать локальные знания, источники и ответственное отношение к природе следующим поколениям.','en'=>'A digital archive can carry local knowledge, sources and care for nature to the next generation.']],
        ];
        foreach ($events as $i => $event) TimelineEvent::updateOrCreate(['date_label' => $event['date_label']], $event + ['source_id' => $i === 2 ? $source?->id : null, 'sort_order' => $i]);

        $articles = [
            ['slug'=>'species-record','title'=>['kz'=>'Атаудың ғылыми ізі','ru'=>'Научная история названия','en'=>'The scientific record of a name'],'excerpt'=>['kz'=>'Алғаш жарияланым дерегі мен таксономиялық жазбаны қатар оқимыз.','ru'=>'Читаем вместе запись о первой публикации и современную таксономическую карточку.','en'=>'Read the original publication record alongside the current taxonomic entry.'],'body'=>['kz'=>'IPNI және Kew жазбалары Tulipa greigii Regel атауы үшін 1873 жылғы Gartenflora басылымын көрсетеді. Одан ертерек кездесуі мүмкін деген әңгімелерді осы библиографиялық фактіден бөлек қарастырған жөн.','ru'=>'Записи IPNI и Kew связывают имя Tulipa greigii Regel с публикацией Gartenflora 1873 года. Возможные более ранние упоминания следует рассматривать отдельно от этого библиографического факта.','en'=>'IPNI and Kew connect the name Tulipa greigii Regel to a 1873 issue of Gartenflora. Possible earlier mentions should be treated separately from this bibliographic record.']],
            ['slug'=>'silk-road-context','title'=>['kz'=>'Жібек жолы: дәлел мен контекст','ru'=>'Шёлковый путь: свидетельства и контекст','en'=>'Silk Roads: evidence and context'],'excerpt'=>['kz'=>'Мәдени байланыстар тарихын өсімдіктің нақты таралуы туралы тұжырымнан ажыратамыз.','ru'=>'Отделяем историю культурных контактов от утверждений о конкретном пути распространения растения.','en'=>'Separate the history of cultural contact from claims about this plant’s route.'],'body'=>['kz'=>'ЮНЕСКО-ның Чанъань–Тянь-Шань дәлізі туралы дерегі өңірдің кең тарихи байланыстарын танытады. Бұл дерек Грейг қызғалдағының сол жолмен саудаға түскенін не Голландияға тасылғанын өздігінен дәлелдемейді.','ru'=>'Материалы ЮНЕСКО о коридоре Чанъань–Тянь-Шань показывают широкий контекст исторических связей региона. Сами по себе они не доказывают торговлю этим тюльпаном или его перевозку в Голландию.','en'=>'UNESCO’s Chang’an–Tianshan corridor record provides broad historical context. By itself it does not prove that Greig’s tulip was traded or transported to the Netherlands along that route.']],
        ];
        foreach ($articles as $i => $article) Article::updateOrCreate(['slug' => $article['slug']], $article + ['source_id' => $i === 0 ? $source?->id : null, 'sort_order' => $i]);

        $legacyMediaPaths = [
            '/images/greig-tulip.svg', '/images/steppe-hero.svg',
            'https://www.biodiversitylibrary.org/pageimage/47574892',
            'https://images.unsplash.com/photo-1770579992716-0ba4ea8b61b4?auto=format&fit=crop&w=1800&q=82',
            'https://images.unsplash.com/photo-1770055438226-acf4619fb694?auto=format&fit=crop&w=1800&q=82',
        ];
        Media::whereIn('path', $legacyMediaPaths)->delete();

        $media = [
            ['kind'=>'flower','title'=>['kz'=>'Грейг қызғалдағы табиғи ортада','ru'=>'Тюльпан Грейга в природной среде','en'=>'Greig’s tulip in its natural setting'],'caption'=>['kz'=>'Ақсу-Жабағылы қорығы, 2014. Фото өлшемі өзгертіліп, WebP-ке түрлендірілген.','ru'=>'Заповедник Аксу-Жабаглы, 2014. Размер фото адаптирован, формат изменён на WebP.','en'=>'Aksu-Zhabagly Nature Reserve, 2014. Resized and converted to WebP.'],'path'=>'/images/tulipa-greigii-wild.webp','credit'=>'V. A. Kovshar · Wikimedia Commons','year'=>'2014','source_url'=>'https://commons.wikimedia.org/wiki/File:Tulipa_greigii_(Aksu_Zhabagly_Nature_Reserve,_Kazakhstan).png','license'=>'CC BY-SA 4.0'],
            ['kind'=>'landscape','title'=>['Ақсу-Жабағылы таулары','Горы Аксу-Жабаглы','Mountains of Aksu-Zhabagly'],'caption'=>['kz'=>'Ақсу-Жабағылы қорығы. Фото өлшемі өзгертіліп, WebP-ке түрлендірілген.','ru'=>'Заповедник Аксу-Жабаглы. Размер фото адаптирован, формат изменён на WebP.','en'=>'Aksu-Zhabagly Nature Reserve. Resized and converted to WebP.'],'path'=>'/images/aksu-zhabagly-mountains.webp','credit'=>'Jack Bartovsky · Wikimedia Commons','year'=>'2022','source_url'=>'https://commons.wikimedia.org/wiki/File:Aksu_Zhabagly_mountains.jpg','license'=>'CC BY-SA 4.0'],
            ['kind'=>'landscape','title'=>['Отырар археологиялық орны','Археологический памятник Отрар','Otrar archaeological site'],'caption'=>['kz'=>'Отырар, 2016. Әуе фотосының өлшемі өзгертіліп, WebP-ке түрлендірілген.','ru'=>'Отрар, 2016. Размер аэрофотографии адаптирован, формат изменён на WebP.','en'=>'Otrar, 2016. Aerial photo resized and converted to WebP.'],'path'=>'/images/otrar-aerial.webp','credit'=>'GaiJorayev · Wikimedia Commons','year'=>'2016','source_url'=>'https://commons.wikimedia.org/wiki/File:Otrar-aerial-view-May-2016-2.jpg','license'=>'CC BY 4.0'],
            ['kind'=>'landscape','title'=>['Қожа Ахмет Ясауи кесенесі','Мавзолей Ходжи Ахмеда Ясави','Mausoleum of Khoja Ahmed Yasawi'],'caption'=>['kz'=>'Түркістан. Фото өлшемі өзгертіліп, WebP-ке түрлендірілген.','ru'=>'Туркестан. Размер фото адаптирован, формат изменён на WebP.','en'=>'Turkistan. Resized and converted to WebP.'],'path'=>'/images/turkistan-mausoleum.webp','credit'=>'Petar Milošević · Wikimedia Commons','year'=>'—','source_url'=>'https://commons.wikimedia.org/wiki/File:Mausoleum_of_Khoja_Ahmed_Yasawi_in_Hazrat-e_Turkestan,_Kazakhstan.jpg','license'=>'CC BY-SA 4.0'],
            ['kind'=>'landscape','title'=>['Шымкент қаласының орталығы','Центр Шымкента','Downtown Shymkent'],'caption'=>['kz'=>'Шымкент, 2015. Фото өлшемі өзгертіліп, WebP-ке түрлендірілген.','ru'=>'Шымкент, 2015. Размер фото адаптирован, формат изменён на WebP.','en'=>'Shymkent, 2015. Resized and converted to WebP.'],'path'=>'/images/shymkent-downtown.webp','credit'=>'Rassim · Wikimedia Commons','year'=>'2015','source_url'=>'https://commons.wikimedia.org/wiki/File:Shymkent_city_downtown.jpg','license'=>'CC BY-SA 3.0'],
            ['kind'=>'archive','title'=>['Gartenflora · 773-тақта','Gartenflora · таблица 773','Gartenflora · plate 773'],'caption'=>['kz'=>'1873 жылғы басылым беті. Қоғамдық игілік белгісіндегі көшірме WebP пішіміне түрлендірілген.','ru'=>'Страница выпуска 1873 года. Копия с отметкой общественного достояния преобразована в WebP.','en'=>'Page from the 1873 issue. Public-domain-marked copy converted to WebP.'],'path'=>'/images/gartenflora-1873.webp','credit'=>'Biodiversity Heritage Library','year'=>'1873','source_url'=>'https://www.biodiversitylibrary.org/page/47574892','license'=>'Public Domain Mark 1.0'],
        ];
        foreach ($media as $i => $item) {
            Media::updateOrCreate(['path' => $item['path']], $item + ['sort_order'=>$i]);
        }
    }
}
